# Generated by Django 3.0.5 on 2020-04-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200401_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.URLField(default='https://i.loli.net/2020/04/08/IHWehlbkQ5nxEma.jpg', verbose_name='封面地址'),
        ),
    ]
